# [Step 2.6: Generate kube join command for joining the node to the Kubernetes cluster and store the command in the file named join-command. ](https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/#step-2-6-generate-kube-join-command-for-joining-the-node-to-the-kubernetes-cluster-and-store-the-command-in-the-file-named-join-command)

- name: Generate join command
  become: true
  shell: |
    kubeadm token create --print-join-command
  register: join_command

- name: Add dummy host to carry join_command to role join_node
  add_host:
    name:   "join_command_dummy_host"
    join_command_sh:  "{{ join_command.stdout }}"