- name: install kubeadm
  apt:
    name: kubectl


## todo k8s

- name: Turn off swap
  cmd: |
    kubectl create namespace klml



cat <<EOF > msgsplit.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: msgsplit
  name: msgsplit
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: msgsplit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: msgsplit
    spec:
      containers:
      - image: klml/msgsplit
        name: msgsplit
        ports:
        - containerPort: 8080
EOF
kubectl apply -f msgsplit.yaml 
kubectl get all -n klml
kubectl get deployments
kubectl expose deployment msgsplit --type=NodePort --name=msgsplit
kubectl get deployments,svc