- name: install apt-transport-https
  apt:
    name: ['apt-transport-https', 'ca-certificates']
    update_cache: yes


- name: Turn off swap
  shell: |
    swapon -s
    swapoff -a


- name: Remove Swap entry from /etc/fstab.
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent


- name: Add an apt signing key for Kubernetes and CRI-o
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23/xUbuntu_20.04/Release.key
    - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key


- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

# from https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems
- name: Adding apt repository for CRIO {{crio_OS}}
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_OS }}/ /
    state: present
    filename: xubuntu.list


- name: Adding apt repository for CRI-O {{ crio_VERSION }}
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_VERSION }}/{{ crio_OS }}/ /
    state: present
    filename: crio.list


- name: install kubelet, kubeadm and crio
  apt:
    name: ['kubeadm', 'kubelet', 'cri-o', 'cri-o-runc']
    update_cache: yes


- name: Make sure a service unit is running
  ansible.builtin.systemd:
    name: crio.service
    state: started
    enabled: yes


## TODO REMOVE
- name: WORKAROUND [kubeadm complains about bridge-nf-call and ip_forward if not using docker runtime](https://github.com/kubernetes/kubeadm/issues/1062)
  block:
  - name: br_netfilter
    community.general.modprobe:
      name: br_netfilter
      state: present

  - name: /proc/sys/net/ipv4/ip_forward set 1
    shell: |
      echo '1' > /proc/sys/net/ipv4/ip_forward