---
- hosts: all
  become: true
  roles:
  - install_nodes

- hosts: control_plane
  become: true
  roles:
  - setup_cluster

- import_playbook: join_nodes.yaml

- hosts: control_plane
  become: true
  roles:
  - setup_network
