- name: kubeadm init on {{ inventory_hostname }}
  shell: |
    kubeadm init --pod-network-cidr=10.244.10.0/16 --apiserver-advertise-address={{ inventory_hostname }}
  ignore_errors: True ## poor mans idempotence